version: "3.5"

# PATH_HOST_REPORTS=./reports PATH_HOST_TESTS=./tests USER=$(id -u):$(id -g) docker-compose run --rm cypress
#                                                     USER=$(id -u):$(id -g) docker-compose run --rm cypress

services:

  cypress:
    image: cypress
    build:
      context: ./docker
      dockerfile: cypress.Dockerfile
      args:
        PATH_WORKDIR: ${PATH_CONTAINER_TESTS}
    user: ${USER}
    volumes:
      # USER passthrough
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # mount tests - readonly
      - ${PATH_HOST_TESTS}/cypress.json:${PATH_CONTAINER_TESTS}/cypress.json:ro
      - ${PATH_HOST_TESTS}:${PATH_CONTAINER_TESTS}/cypress/:ro
      # mount reports - writeable
      - ${PATH_HOST_REPORTS}:${PATH_CONTAINER_TESTS}/reports:rw
      - ${PATH_HOST_REPORTS}/screenshots:${PATH_CONTAINER_TESTS}/cypress/screenshots:rw
      - ${PATH_HOST_REPORTS}/videos:${PATH_CONTAINER_TESTS}/cypress/videos:rw
    command: run --reporter junit --reporter-options "mochaFile=${PATH_CONTAINER_TESTS}/reports/junit.[hash].xml"
