version: "3.5"

# See `cypress_run_example.sh` for shell use

services:

  cypress:
    image: cypress
    build:
      context: ./
      dockerfile: cypress.Dockerfile
      args:
        PATH_WORKDIR: ${PATH_CONTAINER_TESTS}
    user: ${USER}
    volumes:
      # USER passthrough
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # mount tests - readonly
      - ${PATH_HOST_TESTS}/cypress.json:${PATH_CONTAINER_TESTS}/cypress.json:ro
      - ${PATH_HOST_TESTS}:${PATH_CONTAINER_TESTS}/cypress/:ro
      # mount reports - writeable
      - ${PATH_HOST_REPORTS}:${PATH_CONTAINER_TESTS}/reports:rw
      - ${PATH_HOST_REPORTS}:${PATH_CONTAINER_TESTS}/cypress/screenshots:rw
      - ${PATH_HOST_REPORTS}:${PATH_CONTAINER_TESTS}/cypress/videos:rw
    entrypoint: # https://github.com/docker/compose/issues/4993#issuecomment-313201669
      - bash
      - -c
      - HOME=/tmp/ $${PATH_INSTALL}/node_modules/.bin/cypress run --reporter junit --reporter-options "mochaFile=${PATH_CONTAINER_TESTS}/reports/junit.[hash].xml" $$@
      - bash
    #command: run --reporter junit --reporter-options "mochaFile=${PATH_CONTAINER_TESTS}/reports/junit.[hash].xml"
